apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadencereader
  labels:
    app: cadencereader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadencereader
  template:
    metadata:
      labels:
        app: cadencereader
    spec:
      containers:
        - name: cadencereader
          image: cadencereader:latest
          imagePullPolicy: IfNotPresent   # important — otherwise k8s tries to pull from a registry
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 600
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 80
          #   initialDelaySeconds: 3
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: example-db-app
                key: uri
          - name: MIGRATION_FOLDER
            value: "/migrations"
          - name: APP_ENV
            value: "prod"
          - name: VIEW_FOLDER
            value: "/views"

