apiVersion: batch/v1
kind: CronJob
metadata:
  name: rssimport
spec:
  schedule: "15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: rssimport
              image: rssimport:latest
              imagePullPolicy: Never
              resources:
                limits:
                  memory: "200Mi"
                  cpu: "200m"
              env:
              - name: APP_ENV
                value: "prod"
              - name: MIGRATION_FOLDER
                value: "/migrations"
              - name: VIEW_FOLDER
                value: "/views"
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: example-db-app
                    key: uri

          
