// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Blog struct {
	ID                 int32
	Title              string
	ContentDescription string
	RssFeed            string
	CreatedAt          pgtype.Timestamptz
}

type BlogPost struct {
	ID        int32
	BlogID    pgtype.Int4
	Title     string
	Content   string
	CreatedAt pgtype.Timestamptz
}
