// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type Blog struct {
	ID                 int32
	Title              string
	ContentDescription string
	RssFeed            string
	CreatedAt          time.Time
}
