// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type Blog struct {
	ID                 int32
	Title              string
	ContentDescription string
	RssFeed            string
	CreatedAt          time.Time
}

type BlogPost struct {
	ID        int32
	BlogID    sql.NullInt32
	Title     string
	Content   string
	CreatedAt time.Time
}
