// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
)

const createBlog = `-- name: CreateBlog :one
INSERT INTO blog (
  title, content_description, rss_feed
) VALUES (
  $1, $2, $3
)
RETURNING id, title, content_description, rss_feed, created_at
`

type CreateBlogParams struct {
	Title              string
	ContentDescription string
	RssFeed            string
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.db.QueryRow(ctx, createBlog, arg.Title, arg.ContentDescription, arg.RssFeed)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ContentDescription,
		&i.RssFeed,
		&i.CreatedAt,
	)
	return i, err
}
